import {
    Affiliate,
    Campaign,
    Referral,
    DashboardStats
} from './types';

// Generate mock affiliates
export const mockAffiliates: Affiliate[] = [
    // New sample affiliates
    {
        id: '11',
        name: 'Alex Johnson',
        email: 'alex.j@example.com',
        status: 'active',
        earnings: 4780.35,
        referrals: 112,
        joinDate: '2025-04-18',
        avatar: 'https://i.pravatar.cc/150?img=11',
        conversionRate: 0.11,
    },
    {
        id: '12',
        name: 'Sophia Garcia',
        email: 'sophia.g@example.com',
        status: 'active',
        earnings: 6250.80,
        referrals: 143,
        joinDate: '2025-02-22',
        avatar: 'https://i.pravatar.cc/150?img=12',
        conversionRate: 0.13,
    },
    {
        id: '1',
        name: 'John Doe',
        email: 'john.doe@example.com',
        status: 'active',
        earnings: 5240.50,
        referrals: 124,
        joinDate: '2025-01-15',
        avatar: 'https://i.pravatar.cc/150?img=1',
        conversionRate: 0.12,
    },
    {
        id: '2',
        name: 'Jane Smith',
        email: 'jane.smith@example.com',
        status: 'active',
        earnings: 8750.25,
        referrals: 210,
        joinDate: '2024-11-05',
        avatar: 'https://i.pravatar.cc/150?img=2',
        conversionRate: 0.15,
    },
    {
        id: '3',
        name: 'Michael Johnson',
        email: 'michael.j@example.com',
        status: 'inactive',
        earnings: 1250.75,
        referrals: 45,
        joinDate: '2025-03-20',
        avatar: 'https://i.pravatar.cc/150?img=3',
        conversionRate: 0.08,
    },
    {
        id: '4',
        name: 'Sarah Williams',
        email: 'sarah.w@example.com',
        status: 'active',
        earnings: 6840.30,
        referrals: 156,
        joinDate: '2024-09-12',
        avatar: 'https://i.pravatar.cc/150?img=4',
        conversionRate: 0.14,
    },
    {
        id: '5',
        name: 'David Brown',
        email: 'david.b@example.com',
        status: 'pending',
        earnings: 0,
        referrals: 0,
        joinDate: '2025-08-30',
        avatar: 'https://i.pravatar.cc/150?img=5',
        conversionRate: 0,
    },
    {
        id: '6',
        name: 'Emily Davis',
        email: 'emily.d@example.com',
        status: 'active',
        earnings: 4320.15,
        referrals: 98,
        joinDate: '2025-02-18',
        avatar: 'https://i.pravatar.cc/150?img=6',
        conversionRate: 0.11,
    },
    {
        id: '7',
        name: 'Robert Wilson',
        email: 'robert.w@example.com',
        status: 'active',
        earnings: 9150.80,
        referrals: 245,
        joinDate: '2024-08-05',
        avatar: 'https://i.pravatar.cc/150?img=7',
        conversionRate: 0.16,
    },
    {
        id: '8',
        name: 'Jennifer Taylor',
        email: 'jennifer.t@example.com',
        status: 'inactive',
        earnings: 2180.45,
        referrals: 67,
        joinDate: '2025-01-10',
        avatar: 'https://i.pravatar.cc/150?img=8',
        conversionRate: 0.09,
    },
    {
        id: '9',
        name: 'Thomas Anderson',
        email: 'thomas.a@example.com',
        status: 'active',
        earnings: 7520.60,
        referrals: 187,
        joinDate: '2024-10-22',
        avatar: 'https://i.pravatar.cc/150?img=9',
        conversionRate: 0.13,
    },
    {
        id: '10',
        name: 'Lisa Martinez',
        email: 'lisa.m@example.com',
        status: 'pending',
        earnings: 0,
        referrals: 0,
        joinDate: '2025-09-05',
        avatar: 'https://i.pravatar.cc/150?img=10',
        conversionRate: 0,
    },
];

// Generate mock campaigns
export const mockCampaigns: Campaign[] = [
    // New sample campaigns
    {
        id: '9',
        name: 'Winter Collection',
        status: 'active',
        clicks: 4120,
        conversions: 494,
        revenue: 24700,
        startDate: '2025-11-01',
        endDate: '2026-02-28',
        description: 'Winter collection featuring cozy designs for the cold season',
        conversionRate: 0.12,
    },
    {
        id: '10',
        name: 'Mobile App Promotion',
        status: 'active',
        clicks: 3580,
        conversions: 358,
        revenue: 17900,
        startDate: '2025-10-15',
        description: 'Special campaign to promote our new mobile application',
        conversionRate: 0.10,
    },
    {
        id: '1',
        name: 'Summer Sale 2025',
        status: 'active',
        clicks: 5240,
        conversions: 628,
        revenue: 31400,
        startDate: '2025-06-01',
        endDate: '2025-08-31',
        description: 'Summer promotion with 20% discount on all products',
        conversionRate: 0.12,
    },
    {
        id: '2',
        name: 'Black Friday Special',
        status: 'completed',
        clicks: 8750,
        conversions: 1312,
        revenue: 65600,
        startDate: '2024-11-20',
        endDate: '2024-11-30',
        description: 'Black Friday deals with up to 50% off',
        conversionRate: 0.15,
    },
    {
        id: '3',
        name: 'New Product Launch',
        status: 'active',
        clicks: 3150,
        conversions: 252,
        revenue: 12600,
        startDate: '2025-04-15',
        description: 'Launch campaign for our new premium product line',
        conversionRate: 0.08,
    },
    {
        id: '4',
        name: 'Holiday Season',
        status: 'inactive',
        clicks: 6840,
        conversions: 957,
        revenue: 47850,
        startDate: '2024-12-01',
        endDate: '2024-12-31',
        description: 'Holiday season special offers and gift bundles',
        conversionRate: 0.14,
    },
    {
        id: '5',
        name: 'Back to School',
        status: 'active',
        clicks: 4320,
        conversions: 475,
        revenue: 23750,
        startDate: '2025-08-01',
        endDate: '2025-09-15',
        description: 'Special discounts for students and teachers',
        conversionRate: 0.11,
    },
    {
        id: '6',
        name: 'Spring Collection',
        status: 'completed',
        clicks: 5150,
        conversions: 824,
        revenue: 41200,
        startDate: '2025-03-01',
        endDate: '2025-05-31',
        description: 'New spring collection with fresh designs',
        conversionRate: 0.16,
    },
    {
        id: '7',
        name: 'Loyalty Program',
        status: 'active',
        clicks: 2180,
        conversions: 196,
        revenue: 9800,
        startDate: '2025-01-01',
        description: 'Ongoing campaign for loyal customers with special benefits',
        conversionRate: 0.09,
    },
    {
        id: '8',
        name: 'Flash Sale',
        status: 'inactive',
        clicks: 3520,
        conversions: 457,
        revenue: 22850,
        startDate: '2025-07-10',
        endDate: '2025-07-12',
        description: '48-hour flash sale with limited-time offers',
        conversionRate: 0.13,
    },
];

// Generate mock referrals
export const mockReferrals: Referral[] = [
    {
        id: '1',
        affiliateId: '1',
        campaignId: '1',
        date: '2025-06-15',
        status: 'approved',
        commission: 45.75,
        customerEmail: 'customer1@example.com',
    },
    {
        id: '2',
        affiliateId: '2',
        campaignId: '1',
        date: '2025-06-16',
        status: 'approved',
        commission: 52.30,
        customerEmail: 'customer2@example.com',
    },
    {
        id: '3',
        affiliateId: '1',
        campaignId: '3',
        date: '2025-06-18',
        status: 'pending',
        commission: 35.20,
        customerEmail: 'customer3@example.com',
    },
    {
        id: '4',
        affiliateId: '4',
        campaignId: '5',
        date: '2025-08-05',
        status: 'approved',
        commission: 48.90,
        customerEmail: 'customer4@example.com',
    },
    {
        id: '5',
        affiliateId: '7',
        campaignId: '1',
        date: '2025-06-20',
        status: 'rejected',
        commission: 0,
        customerEmail: 'customer5@example.com',
    },
    {
        id: '6',
        affiliateId: '6',
        campaignId: '7',
        date: '2025-06-22',
        status: 'approved',
        commission: 65.40,
        customerEmail: 'customer6@example.com',
    },
    {
        id: '7',
        affiliateId: '9',
        campaignId: '3',
        date: '2025-06-25',
        status: 'pending',
        commission: 42.15,
        customerEmail: 'customer7@example.com',
    },
    {
        id: '8',
        affiliateId: '2',
        campaignId: '5',
        date: '2025-08-10',
        status: 'approved',
        commission: 55.80,
        customerEmail: 'customer8@example.com',
    },
    {
        id: '9',
        affiliateId: '4',
        campaignId: '1',
        date: '2025-06-28',
        status: 'approved',
        commission: 38.60,
        customerEmail: 'customer9@example.com',
    },
    {
        id: '10',
        affiliateId: '7',
        campaignId: '3',
        date: '2025-06-30',
        status: 'pending',
        commission: 47.25,
        customerEmail: 'customer10@example.com',
    },
];

// Generate mock dashboard stats
export const mockDashboardStats: DashboardStats = {
    totalReferrals: 1235,
    totalEarnings: 45250.75,
    conversionRate: 0.12,
    activeAffiliates: 7,
    activeCampaigns: 4,
    recentActivity: [
        {
            id: '1',
            type: 'referral',
            date: '2025-09-18T15:30:00',
            description: 'New referral from John Doe',
            amount: 45.75,
        },
        {
            id: '2',
            type: 'commission',
            date: '2025-09-18T14:15:00',
            description: 'Commission paid to Jane Smith',
            amount: 120.50,
        },
        {
            id: '3',
            type: 'affiliate_joined',
            date: '2025-09-18T10:45:00',
            description: 'David Brown joined as an affiliate',
        },
        {
            id: '4',
            type: 'referral',
            date: '2025-09-17T16:20:00',
            description: 'New referral from Sarah Williams',
            amount: 38.25,
        },
        {
            id: '5',
            type: 'campaign_created',
            date: '2025-09-17T09:30:00',
            description: 'New campaign "Flash Sale" created',
        },
        {
            id: '6',
            type: 'commission',
            date: '2025-09-16T13:10:00',
            description: 'Commission paid to Robert Wilson',
            amount: 95.80,
        },
    ],
    commissionTrends: [
        { date: '2025-03', amount: 3250.75 },
        { date: '2025-04', amount: 4120.30 },
        { date: '2025-05', amount: 3890.45 },
        { date: '2025-06', amount: 5240.80 },
        { date: '2025-07', amount: 6150.25 },
        { date: '2025-08', amount: 7320.60 },
        { date: '2025-09', amount: 5780.90 },
    ],
    topAffiliates: [
        {
            id: '7',
            name: 'Robert Wilson',
            earnings: 9150.80,
            referrals: 245,
            avatar: 'https://i.pravatar.cc/150?img=7',
        },
        {
            id: '2',
            name: 'Jane Smith',
            earnings: 8750.25,
            referrals: 210,
            avatar: 'https://i.pravatar.cc/150?img=2',
        },
        {
            id: '9',
            name: 'Thomas Anderson',
            earnings: 7520.60,
            referrals: 187,
            avatar: 'https://i.pravatar.cc/150?img=9',
        },
        {
            id: '4',
            name: 'Sarah Williams',
            earnings: 6840.30,
            referrals: 156,
            avatar: 'https://i.pravatar.cc/150?img=4',
        },
        {
            id: '1',
            name: 'John Doe',
            earnings: 5240.50,
            referrals: 124,
            avatar: 'https://i.pravatar.cc/150?img=1',
        },
    ],
    campaignPerformance: [
        {
            id: '2',
            name: 'Black Friday Special',
            clicks: 8750,
            conversions: 1312,
            conversionRate: 0.15,
        },
        {
            id: '4',
            name: 'Holiday Season',
            clicks: 6840,
            conversions: 957,
            conversionRate: 0.14,
        },
        {
            id: '1',
            name: 'Summer Sale 2025',
            clicks: 5240,
            conversions: 628,
            conversionRate: 0.12,
        },
        {
            id: '5',
            name: 'Back to School',
            clicks: 4320,
            conversions: 475,
            conversionRate: 0.11,
        },
        {
            id: '3',
            name: 'New Product Launch',
            clicks: 3150,
            conversions: 252,
            conversionRate: 0.08,
        },
    ],
};




